# Generated by Django 5.0 on 2023-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=255)),
                ('cnn', models.IntegerField()),
                ('location_description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('block_lot', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('permit', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('food_items', models.TextField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule', models.CharField(max_length=255)),
                ('dayshours', models.CharField(max_length=255)),
                ('noi_sent', models.CharField(max_length=255)),
                ('approved', models.DateField()),
                ('received', models.DateField()),
                ('prior_permit', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('fire_prevention_districts', models.IntegerField()),
                ('police_districts', models.IntegerField()),
                ('supervisor_districts', models.IntegerField()),
                ('zip_codes', models.IntegerField()),
                ('neighborhoods_old', models.IntegerField()),
            ],
        ),
    ]
